version: '3.3'

services:

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy:/etc/nginx/conf.d
    ports:
      - 80:80
    restart: always
  
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    restart: always

  mongo-express:
    image: mongo-express:0.54
    environment:
      ME_CONFIG_SITE_BASEURL: /mongoexpress
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
    depends_on:
      - "mongo"

  static:
    image: nginx:alpine
    volumes:
      - ./front_page_v1.1/build:/usr/share/nginx/html
      - ./static:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
