version: '3.3'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - "mongo-express"
    ports:
      - "80:80"
      - "443:443"
    restart: always
  
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    restart: always

  mongo-express:
    image: mongo-express:0.54
    environment:
      ME_CONFIG_SITE_BASEURL: /mongoexpress
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev
    depends_on:
      - "mongo"

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./react:/app

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    volumes:
      - ./user:/appsrc
    #command: tail -f /dev/null

  stream:
    build:
      context: ./stream
      dockerfile: Dockerfile
    volumes:
      - ./stream:/appsrc
      - ./stream/config:/config
    command: tail -f /dev/null
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /config/eLuminate-f781d432e057.json